apiVersion: v1
kind: ReplicationController
metadata:
  name: vsts-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vsts-agent
        version: "0.1"
    spec:
      containers:
      - name: vsts-agent
        image: jbogard.azurecr.io/vsts-agent:windows-10.0.14393
        env:
          - name: VSTS_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: vsts
                key: VSTS_ACCOUNT
          - name: VSTS_TOKEN
            valueFrom:
              secretKeyRef:
                name: vsts
                key: VSTS_TOKEN
          - name: VSTS_POOL
            value: k8s-windowsservercore
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      imagePullSecrets:
        - name: vsts-agent-login
      nodeSelector:
        beta.kubernetes.io/os: windows
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock