version: '3'

services:
  ci:
    image: jbogard.azurecr.io/aspnetcore-build:2.0.5-2.1.4-nanoserver-1709
    volumes:
      - .\:c:\src
    working_dir: \src
    environment:
      - "ConnectionStrings:DefaultConnection=Server=test-db;Database=contosouniversity-test;User Id=sa;Password=Pass@word"
    depends_on:
      - test-db
    entrypoint: pwsh
  test-db:
    image: jbogard.azurecr.io/mssql-server-windows-developer
    environment:
      - sa_password=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "6433:1433"
networks:
  default:
    external:
      name: nat
